language: node_js
node_js:
  - "6.9"
install:
  - nvm install -lts
  - npm install npm@latest -g
  - npm install firebase -functions
  - npm install -g firebase-tools
script:
  - echo "deploying"
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"