language: node_js
node_js:
  - "6.9"
install:
  - npm install firebase -fuctions
  - npm install -admin
  - npm install -g firebase-tools
script:
  - echo "deploying"
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"